### PR TITLE
Disable Migrate Config Temporarily  !

### PR DESCRIPTION
**Pull request by capecrusader-121**
Migrate config is crashing app before start, as such a temporary workaround until its fixed.

Also see -->  https://bugs.launchpad.net/lutris-snap/+bug/2028798

@soumyaDghosh  Do correct me whether these will work or not ?

### CODE REVIEW

**Comment by capecrusader-121** [comment]
@soumyaDghosh  merging without review due to severity of problem.

**Comment by soumyaDghosh** [comment]
The migrate config is completely fine. That's why I was taking time to examine more. This config migration tool will only work when, you press yes to the zenity popup. You might have done some mistake.

**Comment by soumyaDghosh** [comment]
kindly share full detailed logs.

**Comment by capecrusader-121** [comment]
@soumyaDghosh  Can we shift this to launchpad for relevancy ?
I have already provided some logs for it.

**Pull request merged**
