### PR TITLE
Automate Snap

### PR DESCRIPTION
**Pull request by capecrusader-121**
See --> https://bugs.launchpad.net/lutris-snap/+bug/2028431

### CODE REVIEW

**Comment by capecrusader-121** [comment]
This will needs fixes, hopefully @saumyaDghosh will look into this.

**Comment by soumyaDghosh** [comment]
`build.yaml` doesn't seem to be of any use. Add your opinion.

**Comment by capecrusader-121** [comment]
@soumyaDghosh  👍🏻  thnx , i am still fresh on this so do whats the best for this snap.

**Comment by soumyaDghosh** [comment]
kindly rename those as requested. local git often ignores to work with capital letters. :sweat_smile:

**Comment by capecrusader-121** [comment]
@soumyaDghosh  Done 👍🏻

**Pull request merged**
